services:
  grafana:
    image: grafana/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_USERS_DEFAULT_THEME=system
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources/
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
  speedtest_exporter:
    image: miguelndecarvalho/speedtest-exporter
    ports:
      - "9798:9798"
    restart: always
    stop_signal: SIGINT
  blackbox_exporter:
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"
    restart: always
    volumes:
      - ./prometheus/exporters/blackbox.yml:/etc/blackbox_exporter/config.yml
  solar_exporter:
    image: stevemarshall/solarman-data-exporter
    environment:
      - INVERTER_ADDRESS=${INVERTER_ADDRESS}
      - INVERTER_SERIAL=${INVERTER_SERIAL}
      - MQTT_ENABLED=False
    ports:
      - "18000:18000"
    restart: always
