services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources/
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
  speedtest_exporter:
    image: miguelndecarvalho/speedtest-exporter
    ports:
      - "9798:9798"
    stop_signal: SIGINT
  blackbox_exporter:
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"
    volumes:
      - ./prometheus/exporters/blackbox.yml:/etc/blackbox_exporter/config.yml
