{
 "title": "Network",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second",
     "legendFormat": "__auto"
    },
    {
     "expr": "speedtest_upload_bits_per_second",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg by(job) (probe_success)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Download",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "DNS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(phase) (probe_dns_duration_seconds)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(instance) (probe_dns_duration_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(phase) (probe_http_duration_seconds)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(instance) (probe_http_duration_seconds)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}